name: lint
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  fmt:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: fmt
      
      - name: Run tests
        run: cargo fmt --all -- --check

  clippy:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      
      - name: Run tests
        run: cargo clippy --all --all-features